# Assignment 3

In [1]:
import numpy as np

### 1. Create a function which creates an n×n array with (i,j)-entry equal to i+j.

In [2]:
def nparr(n):
    arr = np.zeros((n, n))
    for x in range(1,n):
        arr[x:n] = arr[x:n] + 1
        arr[:,x:n] = arr[:,x:n] + 1
    return arr
print(nparr(5))

[[ 0.  1.  2.  3.  4.]
 [ 1.  2.  3.  4.  5.]
 [ 2.  3.  4.  5.  6.]
 [ 3.  4.  5.  6.  7.]
 [ 4.  5.  6.  7.  8.]]


### 2. Create a numpy array which contains odd numbers below 20. Arrange it to a 2x5 matrix. Compute the log of each element

In [3]:
oddns = np.arange(1,20,2)
reshaped = oddns.reshape((2,5))
print("Reshaped Array")
print(reshaped)
logns = np.log(reshaped)
print("Log of Array")
print(logns)

Reshaped Array
[[ 1  3  5  7  9]
 [11 13 15 17 19]]
Log of Array
[[ 0.          1.09861229  1.60943791  1.94591015  2.19722458]
 [ 2.39789527  2.56494936  2.7080502   2.83321334  2.94443898]]


### 3. Create a function which creates an n×n random array. Subtract the average of each row of the matrix 

In [4]:
def avg (a):
    return a-np.average(a)

def nprand(n):
    return np.random.rand(n,n)

arr = nprand(3)
print("Random Array")
print(arr)
new = np.apply_along_axis(avg, 1, arr)
print("Avg Array")
print(new)

Random Array
[[ 0.5378855   0.85059423  0.96913329]
 [ 0.27495396  0.42011504  0.82538333]
 [ 0.61526619  0.4362223   0.38394601]]
Avg Array
[[-0.24798551  0.06472322  0.18326228]
 [-0.23186348 -0.08670241  0.31856589]
 [ 0.13678802 -0.04225587 -0.09453215]]


### 4. Create a function which creates an n×n random array. Write a program to find the nearest value from a given value in the array

In [5]:
def nprand(n):
    return np.random.rand(n,n)

n = 4
val = 0.5

arr = nprand(n)
print("Random Array")
print(arr)
index = np.argmin([np.abs(arr-val)])
print("Nearest Value")
print(arr.flat[index])

Random Array
[[ 0.22642456  0.17353482  0.71666635  0.12015425]
 [ 0.86984192  0.73163239  0.57736296  0.23510477]
 [ 0.9597554   0.55454949  0.33225608  0.0037685 ]
 [ 0.78278823  0.07640925  0.87503717  0.92268746]]
Nearest Value
0.554549486538


### 5. Write a function to check if two random arrays are equal or not

In [6]:
def check_equal(a,b):
    return np.array_equal(a,b)

print(check_equal([1, 2], [1, 2]))
print(check_equal([1, 2], [1, 2, 3]))
print(check_equal([1, 2], [1, 4]))

True
False
False


### 6. Create a function to get the n largest values of an array

In [7]:
def nlarge(arr,n):
    arr = np.sort(arr)[::-1]
    return arr[:n]

n = 4

arr = np.random.randint(9,size=10)
print("Random array")
print(arr)
print(nlarge(arr, n))

Random array
[6 6 7 6 5 0 7 2 4 8]
[8 7 7 6]
